server:
  port: 8010
spring:
  redis:
    host: 106.54.108.197
    port: 6379
    password: myredis
  datasource:
    url: jdbc:mysql://106.54.108.197:5186/im?useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  mvn:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  thymeleaf:
    cache: false
